name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download GNU Arm Embedded Toolchain
      run: bash <(curl -s https://raw.githubusercontent.com/mpekurin/arm-gnu-toolchain-install/main/arm-gnu-toolchain-install.sh) -t arm-none-eabi -l
    - name: make build
      run: make build TOOL_PATH=""
    - name: make link
      run: make link TOOL_PATH=""
